// --- AUTO-GENERATED BY build.rs ---
// DO NOT EDIT THIS FILE MANUALLY

use wasm_bindgen::prelude::*;

/// Unique identifier for animation clips.
/// Defines all available animations in the assets folder.
#[wasm_bindgen]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum AnimationId {
    Placeholder = 0,
    Lunges = 1,
    AbCrunch = 2,
    JumpingJacks = 3,
    BackExtension = 4,
    HandLegTouchJump = 5,
    PushUps = 6,
    SideMuscle = 7,
    FeetForwardJump = 8,
    StraightLegLean = 9,
    ParachuteJump = 10,
    BackwardsLunge = 11,
    OneLegJump = 12,
    CrossedArmsSitup = 13,
    AcDcScissorJump = 14,
    EasierLegLean = 15,
    LegLiftRunning = 16,
    OneLegSquats = 17,
    Planking = 18,
    SquatJumps = 19,
    Burpees = 20,

}

impl AnimationId {
    /// Total number of animations
    pub const COUNT: usize = 21;

    /// Convert to array index
    #[inline]
    pub fn index(self) -> usize {
        self as usize
    }
}
