// Generated by extract_hierarchy.py - DO NOT EDIT by hand!")
use glam::Vec3;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum BoneId {
    Pelvis,
    LeftHip,
    RightHip,
    Spine1,
    LeftKnee,
    RightKnee,
    Spine2,
    LeftAnkle,
    RightAnkle,
    Spine3,
    LeftFoot,
    RightFoot,
    Neck,
    LeftCollar,
    RightCollar,
    Head,
    LeftShoulder,
    RightShoulder,
    LeftElbow,
    RightElbow,
    LeftWrist,
    RightWrist,
}

impl BoneId {
    pub const COUNT: usize = 22;
    pub const ALL: [BoneId; 22] = [
        BoneId::Pelvis,
        BoneId::LeftHip,
        BoneId::RightHip,
        BoneId::Spine1,
        BoneId::LeftKnee,
        BoneId::RightKnee,
        BoneId::Spine2,
        BoneId::LeftAnkle,
        BoneId::RightAnkle,
        BoneId::Spine3,
        BoneId::LeftFoot,
        BoneId::RightFoot,
        BoneId::Neck,
        BoneId::LeftCollar,
        BoneId::RightCollar,
        BoneId::Head,
        BoneId::LeftShoulder,
        BoneId::RightShoulder,
        BoneId::LeftElbow,
        BoneId::RightElbow,
        BoneId::LeftWrist,
        BoneId::RightWrist,
    ];

    pub const fn index(self) -> usize {
        self as usize
    }

    pub const fn from_index(i: usize) -> Option<Self> {
        if i < 22 {
            Some(Self::ALL[i])
        } else {
            None
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct BoneDef {
    pub parent: Option<BoneId>,
    pub length: f32,
    pub direction: Vec3,
}

pub static BONE_HIERARCHY: [BoneDef; BoneId::COUNT] = [
    // 0: Pelvis (Root)
    BoneDef {
        parent: None,
        length: 0.0,
        direction: Vec3::Y,
    },
    // 1: LeftHip (Parent: Pelvis)
    BoneDef {
        parent: Some(BoneId::Pelvis),
        length: 0.1220,
        direction: Vec3::new(0.675, -0.737, -0.025),
    },
    // 2: RightHip (Parent: Pelvis)
    BoneDef {
        parent: Some(BoneId::Pelvis),
        length: 0.1196,
        direction: Vec3::new(-0.659, -0.752, -0.026),
    },
    // 3: Spine1 (Parent: Pelvis)
    BoneDef {
        parent: Some(BoneId::Pelvis),
        length: 0.0943,
        direction: Vec3::Y,
    },
    // 4: LeftKnee (Parent: LeftHip)
    BoneDef {
        parent: Some(BoneId::LeftHip),
        length: 0.3780,
        direction: Vec3::new(0.051, -0.998, -0.028),
    },
    // 5: RightKnee (Parent: RightHip)
    BoneDef {
        parent: Some(BoneId::RightHip),
        length: 0.3780,
        direction: Vec3::new(-0.046, -0.999, -0.028),
    },
    // 6: Spine2 (Parent: Spine1)
    BoneDef {
        parent: Some(BoneId::Spine1),
        length: 0.1226,
        direction: Vec3::Y,
    },
    // 7: LeftAnkle (Parent: LeftKnee)
    BoneDef {
        parent: Some(BoneId::LeftKnee),
        length: 0.4015,
        direction: Vec3::new(0.003, -0.992, -0.130),
    },
    // 8: RightAnkle (Parent: RightKnee)
    BoneDef {
        parent: Some(BoneId::RightKnee),
        length: 0.4015,
        direction: Vec3::new(0.002, -0.992, -0.130),
    },
    // 9: Spine3 (Parent: Spine2)
    BoneDef {
        parent: Some(BoneId::Spine2),
        length: 0.0838,
        direction: Vec3::new(0.000, 0.958, -0.288),
    },
    // 10: LeftFoot (Parent: LeftAnkle)
    BoneDef {
        parent: Some(BoneId::LeftAnkle),
        length: 0.1602,
        direction: Vec3::new(0.078, -0.447, 0.891),
    },
    // 11: RightFoot (Parent: RightAnkle)
    BoneDef {
        parent: Some(BoneId::RightAnkle),
        length: 0.1602,
        direction: Vec3::new(-0.076, -0.448, 0.891),
    },
    // 12: Neck (Parent: Spine3)
    BoneDef {
        parent: Some(BoneId::Spine3),
        length: 0.1968,
        direction: Vec3::Y,
    },
    // 13: LeftCollar (Parent: Spine3)
    BoneDef {
        parent: Some(BoneId::Spine3),
        length: 0.1332,
        direction: Vec3::new(0.411, 0.892, -0.189),
    },
    // 14: RightCollar (Parent: Spine3)
    BoneDef {
        parent: Some(BoneId::Spine3),
        length: 0.1332,
        direction: Vec3::new(-0.411, 0.892, -0.189),
    },
    // 15: Head (Parent: Neck)
    BoneDef {
        parent: Some(BoneId::Neck),
        length: 0.0957,
        direction: Vec3::Y,
    },
    // 16: LeftShoulder (Parent: LeftCollar)
    BoneDef {
        parent: Some(BoneId::LeftCollar),
        length: 0.1114,
        direction: Vec3::X,
    },
    // 17: RightShoulder (Parent: RightCollar)
    BoneDef {
        parent: Some(BoneId::RightCollar),
        length: 0.1114,
        direction: Vec3::new(-0.993, 0.111, 0.030),
    },
    // 18: LeftElbow (Parent: LeftShoulder)
    BoneDef {
        parent: Some(BoneId::LeftShoulder),
        length: 0.2687,
        direction: Vec3::X,
    },
    // 19: RightElbow (Parent: RightShoulder)
    BoneDef {
        parent: Some(BoneId::RightShoulder),
        length: 0.2687,
        direction: Vec3::new(-0.998, 0.044, -0.047),
    },
    // 20: LeftWrist (Parent: LeftElbow)
    BoneDef {
        parent: Some(BoneId::LeftElbow),
        length: 0.2694,
        direction: Vec3::X,
    },
    // 21: RightWrist (Parent: RightElbow)
    BoneDef {
        parent: Some(BoneId::RightElbow),
        length: 0.2694,
        direction: Vec3::new(-0.999, 0.015, -0.049),
    },
];
