use heck::ToPascalCase;
use serde::Deserialize;
use std::env;
use std::fs;
use std::path::Path;

#[derive(Deserialize)]
struct Workout {
    exercises: Vec<Exercise>,
}

#[derive(Deserialize)]
struct Exercise {
    name: String,
}

fn main() {
    // Rerun if workout schema or animations change
    println!("cargo:rerun-if-changed=../src/assets/Workouts/jokkeri_ventti.json");
    println!("cargo:rerun-if-changed=../src/assets/animations");

    // Path to workout dir
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let workout_file = Path::new(&manifest_dir).join("../src/assets/Workouts/jokkeri_ventti.json");

    let workout_data = fs::read_to_string(workout_file).expect("Failed to read workout JSON");
    let workout: Workout =
        serde_json::from_str(&workout_data).expect("Failed to parse workout JSON");

    // Generate enum variants
    let mut variants = String::new();

    // Always add placeholder as the first variant (ID 0)
    variants.push_str("    Placeholder = 0,\n");

    let mut count = 1;

    for exercise in workout.exercises {
        // Convert names like "Ab Crunch" -> "AbCrunch" for enum variant
        let variant_name = exercise.name.to_pascal_case();

        // Handle names that result in illegal identifiers
        let variant_name = if variant_name
            .chars()
            .next()
            .map_or(false, |c| c.is_ascii_digit())
        {
            format!("_{}", variant_name)
        } else {
            variant_name
        };

        variants.push_str(&format!("    {} = {},\n", variant_name, count));
        count += 1;
    }

    // Generate file content - ONLY AnimationId
    let content = format!(
        r#"// --- AUTO-GENERATED BY build.rs ---
// DO NOT EDIT THIS FILE MANUALLY

use wasm_bindgen::prelude::*;

/// Unique identifier for animation clips.
/// Defines all available animations in the assets folder.
#[wasm_bindgen]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum AnimationId {{
{}
}}

impl AnimationId {{
    /// Total number of animations
    pub const COUNT: usize = {};

    /// Convert to array index
    #[inline]
    pub fn index(self) -> usize {{
        self as usize
    }}
}}
"#,
        variants, count
    );

    // Write to separated file
    let dest_path = Path::new(&manifest_dir).join("src/bone/anim_ids.rs");
    fs::write(&dest_path, content).expect("Failed to write anim_ids.rs");
}
