use heck::ToPascalCase;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // Rerun if assets change
    println!("cargo:rerun-if-changed=../src/assets/animations");

    // Path to animations dir
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let assets_dir = Path::new(&manifest_dir).join("../src/assets/animations");

    // Read all JSON files
    let mut files: Vec<PathBuf> = fs::read_dir(&assets_dir)
        .expect("Failed to read animations directory")
        .filter_map(|entry| {
            let entry = entry.ok()?;
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) == Some("json") {
                Some(path)
            } else {
                None
            }
        })
        .collect();

    // Sort to ensure stable ID generation
    files.sort();

    // Generate enum variants
    let mut variants = String::new();
    let mut count = 0;

    for (i, path) in files.iter().enumerate() {
        let filename = path.file_stem().unwrap().to_str().unwrap();
        // Convert snake_case filename to PascalCase variant
        let variant_name = filename.to_pascal_case();

        // Special case handling if names start with digits (not allowed in Rust)
        // Check if first char is digit, if so prepend 'N' or similar?
        // Our files seem safe, but let's be safe.
        let variant_name = if variant_name
            .chars()
            .next()
            .map_or(false, |c| c.is_ascii_digit())
        {
            format!("_{}", variant_name)
        } else {
            variant_name
        };

        variants.push_str(&format!("    {} = {},\n", variant_name, i));
        count += 1;
    }

    // Generate file content - ONLY AnimationId
    let content = format!(
        r#"// --- AUTO-GENERATED BY build.rs ---
// DO NOT EDIT THIS FILE MANUALLY

use wasm_bindgen::prelude::*;

/// Unique identifier for animation clips.
/// Defines all available animations in the assets folder.
#[wasm_bindgen]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum AnimationId {{
{}
}}

impl AnimationId {{
    /// Total number of animations
    pub const COUNT: usize = {};

    /// Convert to array index
    #[inline]
    pub fn index(self) -> usize {{
        self as usize
    }}
}}
"#,
        variants, count
    );

    // Write to separated file
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let dest_path = Path::new(&manifest_dir).join("src/bone/anim_ids.rs");
    fs::write(&dest_path, content).expect("Failed to write anim_ids.rs");
}
